### ISSUE TITLE
Consolidate duplicate patient IDs and CMO patient IDs that are missing the leading "C-" (some cases of this)

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1012]
![image.png](https://images.zenhubusercontent.com/5ca7937785daed12b0c3728d/03aa3f3b-aebd-4a97-a1a8-f32420e65d48)

Confirm whether these are all unique smile patient IDs (UUIDs) or are we just viewing duplicate results in the table?

**Another example**

Correcting the new patient ID using the `MDB_STREAM.server.correct-cmoptid` topic does not completely take care of the patient swapping. In the example below the clinical samples were correctly associated with the patient having CMO ID `C-000511` but their pre-existing relationship to patient node with CMO ID `000511` was not dropped. This should be a pretty easy fix as far as db operations go within the `smile-server` codebase.

Next step(s) would involve identifying all such cases and running a corrective series of published messages to fix the data. 

![image.png](https://images.zenhubusercontent.com/5ca7937785daed12b0c3728d/fb7835ab-696c-411d-b4b9-98f0eada01ef)

**Comment by qu8n** [comment]
Closed this ticket because I found that the duplicates seen on the frontend will be resolved automatically once duplicates in the database are resolved. This is because the frontend's Patients view displays each row as a PatientAlias node and not as a Patient node.
