### ISSUE TITLE
[smile-server] bug fix for "MDB_STREAM.server.correct-cmoptid" workflow

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1013]
Related to [#1012](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1012)

CMO patient ID correction workflow updates samples to the correct Patient ID but the pre-existing relationship to the incorrect `Patient` node isn't removed. 

Info taken from #1012

Correcting the new patient ID using the `MDB_STREAM.server.correct-cmoptid` topic does not completely take care of the patient swapping. In the example below the clinical samples were correctly associated with the patient having CMO ID `C-000511` but their pre-existing relationship to patient node with CMO ID `000511` was not dropped. This should be a pretty easy fix as far as db operations go within the `smile-server` codebase.

Next step(s) would involve identifying all such cases and running a corrective series of published messages to fix the data. 

![image.png](https://images.zenhubusercontent.com/5ca7937785daed12b0c3728d/fb7835ab-696c-411d-b4b9-98f0eada01ef)

**Comment by qu8n** [comment]
@n1zea144 tagging you here for your reference. Whenever you get to this ticket, let me know if you'd like to discuss together how we should handle all the edge cases when modifying the existing Smile data (unless we're reimporting all data from LIMS). I assume that we will modify the dev server data first before touching prod. Let me know if there is anything here that I can help with.
