### ISSUE TITLE
[smile-server] Make SMILE republish a request when the `isCmoRequest` changes

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1040]
Danielle reached out to us about these requests that were not updated on 11/1:
06437_V
15063_B

Question for PMs, Ben: Is `isCmoRequest` something we want to support allowing authorized users to override from the dashboard or can/should it remain a protected field that is only updated through the IGO marked delivery process?

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1040?planning-poker) with Zenhub @qu8n
