### ISSUE TITLE
Identify duplicate nodes in the db by different node types

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1045]
**Patient nodes** 

Patient duplicate nodes were fixed approximately around August 5th, 2023. "Duplicates" were found by CMO patient ID barcode and were merged to single records during these updates.

The screenshot here shows that the records displayed on the dashboard patient view table are actually the same record as per the SMILE patient ID (uuid).
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45e8a6779a0616d8a8d913d7599a90a457175660/image.png)

Searching the database for records with aliases matching the DMP patient ID returns a single record:
```
match (pa:PatientAlias{value:"P-0023860"})-[:IS_ALIAS]->(p:Patient) return p
```
**To definitively rule out issues with the database itself we should attempt to identify if there are in fact any duplicates of any node (data) type.** 
I'm leaning towards this duplicate display of data being a result of the dashboard frontend rendering results that are non-unique. One solution would be to perform some data manipulation that "unique-ifies" the results returned by the Apollo Graphql client. Another solution would be to modify the apollo graphql query itself to only return distinct results. 

TODO: generalize query for finding nodes where pa.value matches across multiple p nodes

Find patient nodes that point to aliases that are the same. (related to 1008)

**Comment by ao508** [comment]
As it stands, these checks and fixes would rely on a suite of scripts. It would be ideal if these could be consolidated. Some further thought should be put into how this should be executed and at what frequency as there were quite a few cases of the duplicate patient nodes that I had to resolve manually. I'll summarize my findings in another document.
