### ISSUE TITLE
Investigate samples with missing `fastQs` and no `IgoComplete` that received a sample label

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1111]
Reported by Jennifer in the PM Slack channel [here](https://mskcmo.slack.com/archives/C01HQ1ZAUUU/p1710261460010659) for request [12582_AR](https://smile.mskcc.org:3006/requests/12582_AR). 

Out of this request's 55 samples, 10 were undelivered due to them missing `fastQs` and not being `IgoComplete`. 

7 of these 10 samples received a sample label, which is unexpected -- we'll need to investigate why this happened.

**Comment by ao508** [comment]
After looking at the JSON sent by IGO LIMS, it appears that some samples were delivered with a predetermined CMO sample label. You can quickly spot these cases as the samples with labels that only end with `-d` and not `-dNN` where `NN` is the 2 digit nucleic acid type increment

**Comment by ao508** [comment]
Jen to dig into this further and follow up with IGO
