### ISSUE TITLE
Enforce fuzzy search logic for `endUsers` and `pmUsers` on Cohorts page

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1124]
Currently on the Smile dashboard, when users perform a single-value search, the dashboard would run a fuzzy search, looking through data and returns any that contains the search term. On the other hand, when users perform a bulk search, the dashboard would run an exact search, looking through data and returns only those that exactly match the search term.

The above search logic isn't currently applied to the `endUsers` and `pmUsers` fields on Cohorts page. Unlike other fields which have a data type of string, these fields have a data type of an array of strings. The only relevant GraphQL filter parameter suffix for this data type is `_INCLUDES`. This is what we're currently using, and I assume that it runs an exact search through each element of the array.

We'll likely have to write a resolver to handle querying these fields. One possible solution in the resolver is to iterate through each element of the array of strings and perform fuzzy/exact search, depending on the number of search terms from users.

TODO:
- [x] DB  - transform existing pmUsers, endUsers into flattened [comma space]-delimited strings
- [ ] smile-server models: might be able to leave as List<String> (need to confirm) but need to apply ListString converter annotation to Neo4j @/NodeEntity model

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1124?planning-poker) with Zenhub @qu8n
