### ISSUE TITLE
Bug: patient record duplicates & missing samples when querying by DMP Patient ID

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1143]
From Jen's email titled "PM Dashboard bug".

> When querying a CMO patient ID, the ID was returned twice but only the first line generated the sample view when the ‘View’ button was hit. 
<img width="1775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b760506e8a709cc247ef6185de7ca755df5b860/thumbnail_image001.png" alt="thumbnail_image001.png" />
<img width="1775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d452f806e5ca3b2bbe2934e83d0d53efeab51e5/image002.png" alt="image002.png" />
<img width="1775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df1354442a67c7350af3817e2a56e601cc9f93f7/thumbnail_image003.png" alt="thumbnail_image003.png" />

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1143?planning-poker) with Zenhub @qu8n
