### ISSUE TITLE
[dashboard] Add back CMO/DMP Patient ID in the Patient Samples popup

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1149]
After #1143, the Patients Samples popup will have the heading of `Viewing Patient's Samples`. We want to turn this back to either "Viewing CMO Patient ID <id>" or "Viewing DMP Patient ID <id>".

Context: #1143 fixes the patient duplicates issue. After this work, the frontend needs additional refactoring before it could access the CMO/DMP Patient ID in the sample popup view. We decided to not include that refactoring as part of #1143.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1149?planning-poker) with Zenhub @qu8n

**Comment by qu8n** [comment]
Closed via #1222
