### ISSUE TITLE
[dashboard]  Implement validation for `costCenter` field in the Cohort Samples view

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1150]
Format: `<5 digits>-<5 digits>` (without the brackets)

Questions:
- Should we validate text input (1) as the user types or (2) after they finish editing? #2
- Should we prevent users from submitting changes if some validation fails?
  - If yes, what should the UI look like? "Submit Updates" button greyed out + column tooltip + modal after they finish editing

Dev branch: https://github.com/mskcc/smile-dashboard/pull/124

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1150?planning-poker) with Zenhub @qu8n
