### ISSUE TITLE
[dashboard] Sort data on all pages excluding Samples

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1152]
Sort records in all pages (e.g. Cohorts by Initial Cohort Delivery Date, Patients by CMO Patient ID ascending) to improve readability and intuitiveness.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1152?planning-poker) with Zenhub @qu8n
