### ISSUE TITLE
Change the billing message handler to also accept `dataCustodian` and `accessLevel` fields

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1166]
Added as interrupt after discovering that these two fields would not be updated if changed through the dashboard.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1166?planning-poker) with Zenhub @qu8n
