### ISSUE TITLE
[dashboard] Auto-sort data by latest updates/imports for Requests and Cohorts views

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1196]
This is different from #1152 which makes all of the columns sortable. The reason why the columns aren't auto-sortable is due to many of the data elements being nested properties of the main data source. 

The changes from this task would at least always show the latest records updated/imported at the top.

Field to import by for each page:
 - patients: not needed
 - requests: importDate (surface this field as well)

We're excluding Samples to await on #1221.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1196?planning-poker) with Zenhub @qu8n

**Comment by ao508** [comment]
@qu8n Can you update the labels to "READY TO DEPLOY" or "DEPLOYED" when appropriate?

**Comment by qu8n** [comment]
> @qu8n Can you update the labels to "READY TO DEPLOY" or "DEPLOYED" when appropriate?

@ao508 Yep, let me do that in the late afternoon.
