### ISSUE TITLE
Enable column filters for boolean and date columns

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1229]
We'll need to figure out how to pass along `filterModel` value (the active filter) inside a GraphQL query so we can access it inside the custom resolvers. Will require some research as `filterModel` can't just be passed into the `where`, `options`, or as another property inside a request

We'll also need to move the sorting and filtering client-side logic of Cohorts view to the GraphQL server as well to be consistent.

**Updated scope:** Add filter to all columns that have set values defined (i.e., yes/no, and dates)

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1229?planning-poker) with Zenhub @qu8n

**Comment by qu8n** [comment]
[#172](https://github.com/mskcc/smile-dashboard/pull/172)
