### ISSUE TITLE
Populate cancer type/cancer type detailed on import of research and clin samples in SMILE

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1233]

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1233?planning-poker) with Zenhub @qu8n

**Comment by ao508** [comment]
With the way we are approaching #1232, I don't think we actually need to do this work in the `smile-server` codebase now that I'm thinking about it. I'm going to label this card as "paused" for now @qu8n

**Comment by qu8n** [comment]
@ao508 Makes sense. Thank you
