### ISSUE TITLE
Explore use case displaying 500+ rows of Samples data

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1239]
Kirsten reported recently having to scroll past 500 rows on the Samples page and saw the warning "You've reached the maximum number of samples that can be displayed. Please refine your search to see more samples."

This is currently a feature, not a bug, as we initially didn't expect PMs to manually scroll this far. The current understanding is that PMs' workflow often involves searching for specific data by their IDs.

Let's discuss the scenarios in which PMs would scroll past 500 rows.

Some potential solutions: (in increasing effort amount)
- Make the 500-row limit message clearer so users know that this isn't a bug
- Increase the fixed row limit (e.g. to 1,000 rows)
- Implement infinite scrolling so users can keep scrolling through the entire samples data set

**Comment by ao508** [comment]
Paused for now as the need for this may not be necessary anymore once the filtering oncotree codes, ct + ctdetailed are added.
