### ISSUE TITLE
Enable searching `cancerType` and `cancerTypeDetailed` fields in the Samples views

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1244]
We added these fields as part of #1232.

This implement would require a GraphQL custom resolver for the Samples query. We can't use the default resolver as these fields don't exist in the Neo4j database.

In this new Samples custom resolver, we need to somehow extrapolate oncotree codes from the possible `cancerType` and `cancerTypeDetailed` strings in the search values, and then pass those oncotree codes to the Samples query to the Neo4j database.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1244?planning-poker) with Zenhub @qu8n
