### ISSUE TITLE
Investigate duplicate Patient nodes

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1267]
**DONE CONDITIONS**
- duplicate patient nodes are merged
- a script is checked into `smile-utils` repo to monitor/catch cases in the future

Duplicate cases found:

```
cmoId	pCount	ptids
"C-W38Y0E"	2	["f3d9fc10-8101-4812-aa1d-61f9ff8f7e74", "a22133fd-cb3e-4ade-8f84-e673fa5e0482"]
"C-KXFN5P"	2	["f620b699-74d0-486c-a176-d2dd92833ffd", "1279a91b-edf1-409c-812b-c6a14d4b97f1"]
"C-9YUX62"	2	["0235eea8-0a4d-4dd6-8907-3fda25263c93", "992cb66e-b5ee-40b3-8f03-24f02e555640"]
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1267?planning-poker) with Zenhub @qu8n

**Comment by ao508** [comment]
Script added: https://github.mskcc.org/cmo/smile-utils/tree/main/duplicate_patient_nodes
