### ISSUE TITLE
Patient count is not accurate when filtering records in Patient  view tab

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1274]
<img width="1011" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG0wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7418c506017692441f8cba68c3a29c6be9d3a712/image.png" alt="image.png" />

**Comment by qu8n** [comment]
Pausing for now as we aren't able to reproduce this bug.
