### ISSUE TITLE
Regenerate CMO Sample ID for sample 12356_AI_31

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1290]
Confirm what patient ID this sample should have. 
- patient ID = C-NXAND3
- sample type = Tumor

Revert changes that were made 10/4/24

**Comment by ao508** [comment]
Summary:
- we deleted updates that were submitted 2024-10-04
- we updated (via dashboard) the cmo patient id, sample type, and tumor or normal values
- changes were received and updated label were successful.
