### ISSUE TITLE
[dashboard] Make the Patients page's default sort to be by importDate

### ISSUE THREAD

**Issue by qu8n** [mskcc/smile-server#1321]

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1321?planning-poker) with Zenhub @qu8n

**Comment by qu8n** [comment]
[#170](https://github.com/mskcc/smile-dashboard/pull/170)
