### ISSUE TITLE
[dashboard] As first pass - add column that shows historical CMO labels as comma-delim list

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1340]
For this first pass the exported file will also have this column displayed as it is in the dashboard.

<img width="1377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG51Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e64df9ac6d4070632558eab254e172c9b73613b/image.png" alt="image.png" />

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1340?planning-poker) with Zenhub @qu8n

**Comment by qu8n** [comment]
[#173](https://github.com/mskcc/smile-dashboard/pull/173)
