### ISSUE TITLE
[dashboard] SMILE Patient ID Query 12405_I

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1342]
**Reported by Jen:**

I know we are still resolving CMO Sample ID issues but just wanted to escalate potential bugs I found with the PHI patient search for when bandwidth allows:
When I query the 19 CMO-Patient IDs from 12405_I with PHI enabled and successfully logged in—the Patient search returns 39 matching patients. Certain MRNs are duplicated with a line item for DMP Sample ID and 12-245 response and another line item for CMO Sample IDs. The report looks similar to below. I have redacted the MRN.
 
| Patient MRN | CMO Patient ID | DMP Patient ID | 12-245 Part A | 12-245 Part C | # Samples | Sample IDs |
|-|-|-|-|-|-|-|
| REDACTED|C-1XEP2H|P-0008643|YES|NO|1|P-0008643-T01-IM5|
|REDACTED|C-1XEP2H|P-0008643|||1|C-1XEP2H-P001-d01|
 
 
Then when I query the same 19 MRNs in MPath, 18 of 19 do return DMP Patient IDs whereas only 4 of 19 return DMP Patient IDs in SMILE and I am not immediately seeing any pattern across assay.

**Comment by qu8n** [comment]
[#172](https://github.com/mskcc/smile-dashboard/pull/172)
