### ISSUE TITLE
Support multiple streams per running application

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#637]
Cannot use the same consumer for multiple streams (problematic). 

Rearchitect messaging lib to allow multiple streams/consumers

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/637?planning-poker) with ZenHub @divyamadala30

**Comment by divyamadala30** [comment]
![Screen Shot 2022-04-04 at 9.05.49 AM.png](https://images.zenhubusercontent.com/5f5a235fd9cf66a9a30c38fc/451d9efc-3544-45c4-986a-da2595c2f996)![Screen Shot 2022-04-04 at 9.05.56 AM.png](https://images.zenhubusercontent.com/5f5a235fd9cf66a9a30c38fc/3adcc592-0d0c-44a4-af80-497349a7f58c)

**Comment by divyamadala30** [comment]
link mentioned in the screenshots above: https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/replication#sources

**Comment by divyamadala30** [comment]
- Test sample PUB/SUB consumers with empty filter
- Test sample PUB/SUB consumers where they only publish to the stream they're built on and subscribe to others
- Tweaking messaging-java to allow multiple ocnsumers
