### ISSUE TITLE
Validate CVR Fetch into SMILE

### ISSUE THREAD

**Issue by n1zea144** [mskcc/smile-server#666]
I did a quick spot check between mskimpact samples that were fetched from CVR on 4/21.  It seems like some samples did not get into graph (note I'm ignoring heme samples for now)

Here is a list of samples that are in cvr_data.json:

```
      "dmp_sample_id" : "P-0013121-T05-IM6",
      "dmp_sample_id" : "P-0018318-T01-IM6",
      "dmp_sample_id" : "P-0023858-T01-IM6",
      "dmp_sample_id" : "P-0028912-T01-IM6",
      "dmp_sample_id" : "P-0035209-T06-IM7",
      "dmp_sample_id" : "P-0035209-T07-IM7",
      "dmp_sample_id" : "P-0035209-T08-IM7",
      "dmp_sample_id" : "P-0035209-T09-IM7",
      "dmp_sample_id" : "P-0072535-T01-IM7",
      "dmp_sample_id" : "P-0075428-T01-IM7",
      "dmp_sample_id" : "P-0075798-T05-IM7",
      "dmp_sample_id" : "P-0077162-T02-IM7",
      "dmp_sample_id" : "P-0077210-T02-IM7",
      "dmp_sample_id" : "P-0077660-T01-IM7",
      "dmp_sample_id" : "P-0077776-T01-IM7",
      "dmp_sample_id" : "P-0077777-T01-IM7",
      "dmp_sample_id" : "P-0077779-T01-IM7",
      "dmp_sample_id" : "P-0077945-T01-IM7",
      "dmp_sample_id" : "P-0077953-T01-IM7",
      "dmp_sample_id" : "P-0077954-T01-IM7",
      "dmp_sample_id" : "P-0077955-T01-IM7",
      "dmp_sample_id" : "P-0077956-T01-IM7",
      "dmp_sample_id" : "P-0077957-T01-IM7",
      "dmp_sample_id" : "P-0077958-T01-IM7",
      "dmp_sample_id" : "P-0077959-T01-IM7",
      "dmp_sample_id" : "P-0077960-T01-IM7",
      "dmp_sample_id" : "P-0077961-T01-IM7",
      "dmp_sample_id" : "P-0077962-T01-IM7",
      "dmp_sample_id" : "P-0077963-T01-IM7",
      "dmp_sample_id" : "P-0077970-T01-IM7",
      "dmp_sample_id" : "P-0077971-T01-IM7",
      "dmp_sample_id" : "P-0077972-T01-IM7",
      "dmp_sample_id" : "P-0077998-T01-IM7",
      "dmp_sample_id" : "P-0078006-T01-IM7",
      "dmp_sample_id" : "P-0078008-T01-IM7",

```

Here is list of ids after running query

match p=(a:SampleAlias)-[r:IS_ALIAS]->(s:Sample) where s.sampleCategory = "clinical" return (a.value);

> P-0013121-T05-IM6
> P-0035209-T06-IM7
> P-0035209-T07-IM7
> P-0035209-T08-IM7
> P-0035209-T09-IM7
> P-0072535-T01-IM7
> P-0075428-T01-IM7
> P-0075798-T05-IM7
> P-0077162-T02-IM7
> P-0077210-T02-IM7
> P-0077776-T01-IM7
> P-0077777-T01-IM7
> P-0077779-T01-IM7
> P-0077945-T01-IM7
> P-0077953-T01-IM7
> P-0077954-T01-IM7
> P-0077955-T01-IM7
> P-0077956-T01-IM7
> P-0077957-T01-IM7
> P-0077958-T01-IM7
> P-0077959-T01-IM7
> P-0077960-T01-IM7
> P-0077961-T01-IM7
> P-0077962-T01-IM7
> P-0077963-T01-IM7
> P-0077970-T01-IM7
> P-0077971-T01-IM7
> P-0077972-T01-IM7
> P-0077998-T01-IM7
> P-0078006-T01-IM7
> P-0078008-T01-IM7
> P-0015770-T03-IH4
> P-0051524-T10-IH4
> P-0052771-T05-IH4
> P-0060352-T02-IH4
> P-0077914-T01-IH4

**Comment by ao508** [comment]
@n1zea144 there were some duplicates in the list of ids you provided above that were from the json file

these are the samples that didn't make it into smile:

```
< P-0018318-T01-IM6
< P-0023858-T01-IM6
< P-0028912-T01-IM6
< P-0077660-T01-IM7
```

all which failed to get consumed on CVR's end so they wouldn't be getting imported into SMILE

**Comment by n1zea144** [comment]
Oh great.  It didn't occur to me that we check in the JSON, but that make sense now.
