### ISSUE TITLE
Ability to sort or filter requests

### ISSUE THREAD

**Issue by n1zea144** [mskcc/smile-server#684]
Project Managers should be able to sort or filter requests by any column in the table.

Note: Jen to provide updated prototype + screen shot of IGO request tracker react app

TODO:
- [x] add sorting to recent request deliv's table
- [ ] add sorting to request view table
- [ ] add filtering to recent request deliv's table
- [ ] add filter to request view table

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/684?planning-poker) with ZenHub @divyamadala30
