### ISSUE TITLE
Create "Hello World" starter setup for Dashboard

### ISSUE THREAD

**Issue by n1zea144** [mskcc/smile-server#687]
We need to create a starter setup project with technologies of our chosen that we can give to MLH fellow to start developing on.  Current tech stack used by cBioPortal includes:

This is the place to start:
CreateReactApp (https://create-react-app.dev/)

These are "dependencies":
React-Bootstrap (https://react-bootstrap.github.io/)
Mobx (https://mobx.js.org/README.html)
Typescript (https://www.typescriptlang.org/)
React Router (https://reactrouter.com/)
React Table (https://react-table.tanstack.com/)

We should also make sure to support unit testing.

Unit tests:
- dealing with data that we're displaying on a dashboard
- framework integration, react app config file

This may come in handy for dashboard development
https://product.design.dev.aws.mskcc.org/

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/687?planning-poker) with ZenHub @divyamadala30
