### ISSUE TITLE
LIMS data dump for specific sample attributes

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#695]
Note: the data dump provided by David on May 4th contains only the cmo ID and igo ID mapping. 

First pass:
- request, isCmoRequest , sample igo id, sample igo complete status

python libraries that would be useful
- sys
- os
- csv
- json
- urllib

---

This can be done by modifying the output of the sample publisher LIMS mode.

Attributes to collect for each sample:
- delivery date (epoch timestamp)
- request id
- sample igo id
- cmo sample name
- baitset
- cmo patient id
- igo complete
- cmo sample class
- specimen type
- sample type (from cmoSampleIdFields -> sampleType)
- has non-empty fast qs (dont want to have to write the whole list of strings, just whether this field is present and non-empty should suffice)
- naToExtract (from cmoSampleIdFields -> naToExtract)

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/695?planning-poker) with ZenHub @divyamadala30

**Comment by shalabhsuman** [comment]
This is how I am planning the format for output report will look like:

![Screen Shot 2022-06-08 at 9.14.00 AM.png](https://images.zenhubusercontent.com/629f86429173237d1c9c3599/b9afdf05-ed2e-41d2-be84-5c37c13f37fc)
