### ISSUE TITLE
Consistency Checker - java.lang.Exception throw during startup

### ISSUE THREAD

**Issue by n1zea144** [mskcc/smile-server#736]
The following is seen during consistency checker service startup:

`2022-07-18 20:06:30.373  INFO 1 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation should only be used on methods with parameters: private void org.mskcc.smile.service.impl.MessageHandlingServiceImpl.initFileUtilLogger() throws java.lang.Exception`

**Comment by ao508** [comment]
@n1zea144 this looks like a missing property?

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/736?planning-poker) with ZenHub @divyamadala30
