### ISSUE TITLE
Deploy latest docker images for smile services (including neo4j update)

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#756]
Note: 
- clean up images from dockerhub that were built/used for testing purposes

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/756?planning-poker) with ZenHub @divyamadala30

**Comment by divyamadala30** [comment]
PR: https://github.mskcc.org/cmo/cmo-metadb-deployment/pull/60/commits
