### ISSUE TITLE
Smile-server warning logs (conflict between JDK 11 and Neo4J 4.4.9)

### ISSUE THREAD

**Issue by divyamadala30** [mskcc/smile-server#760]
Found the warning message in smile-server and label-generator logs. This could be related to Spring Data Neo4j.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/smile-server/smile_server.jar!/BOOT-INF/lib/spring-core-5.2.8.RELEASE.jar!/) to field java.lang.Enum.name
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Environment:

- docker-compose neo4j version 4.4.9

- smile-server uses `<neo4j-java-driver.version>4.4.9</neo4j-java-driver.version>`

- label-generator uses `<smile_server.version>1.3.9.RELEASE</smile_server.version>`

Possible solutions:

- Supress warnings by adding `--add-opens java.base/java.lang=ALL-UNNAMED`

- Downgrading Java version

- Upgrading spring boot version 5.0+

- Ensure spring boot devtools isn't being used

References:
https://stackoverflow.com/questions/62383718/spring-boot-and-enums-cause-an-illegal-reflective-access-operation
https://github.com/spring-projects/spring-framework/issues/22713

**Comment by n1zea144** [comment]
Hi @divyamadala30 I would go with adding the "--add-opens...." argument to JVM startup.  The following [Baeldung](https://www.baeldung.com/java-illegal-reflective-access) page made the issue more digestible and seems the add-opens solution restores the Java8 behavior.
