### ISSUE TITLE
Verify that "generate report" still works in sample table and observes the filtering

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#821]
If filtering results in the sample table then the "generate report" button should only export data for the samples that were filtered. 

i.e., if samples are filtered to only tumor samples then the report generated should only contain tumor samples

It is possible that there isn't any work involved for this card.

Dev branch: https://github.com/mskcc/smile-dashboard/tree/dev-sample-filtering

**Comment by shalabhsuman** [comment]
We verified that its already working as expected.

**Comment by Jennnyyy** [comment]
I have verified that the samples are filtered and are being downloaded when Tumor or Normal is searched for.
