### ISSUE TITLE
Install system dependencies on the new production and dev machines.

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#824]
**Still left to do:**
- [x] JDK on dev machine (done 11/21)
- [ ] JDK on prod machine (waiting)

Done condition: all required system dependencies have been installed on both of the new machines.

Note: docker/docker-compose might already be installed on these new machines by the open sys team. Confirm if this is the case or not and if not then submit a request to install these according to the same versions we are using already.

Resources:
- [setup-system-dependencies.sh](https://github.mskcc.org/cmo/cmo-metadb-configuration/blob/master/scripts/setup-system-dependencies.sh)

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/824?planning-poker) with Zenhub @divyamadala30

**Comment by divyamadala30** [comment]
Task has been assigned to Virtual Infra and Opensys team

**Comment by ao508** [comment]
A ticket has been created to install a JDK (only a JRE was installed)
