### ISSUE TITLE
09780_N redaction (whole request)

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#897]

**Comment by divyamadala30** [comment]
IGO ID
09780_N_34
09780_N_33
09780_N_42
09780_N_27
09780_N_41
09780_N_25
09780_N_29
09780_N_26
09780_N_36
09780_N_39
09780_N_37
09780_N_38
09780_N_32
09780_N_24
09780_N_40
09780_N_35
09780_N_31
09780_N_28
09780_N_30
