### ISSUE TITLE
Support bulk searching requests for the request view table.

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#976]
Based on [#975](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/975)

Implements bulk searching requests when viewing the request page.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/976?planning-poker) with Zenhub @qu8n

**Comment by qu8n** [comment]
Next steps after discussing with Aaron, Pavitra, and Jen:
- Implement exact matching when there are multiple values in a search query (via the `_IN` operator) and fuzzy/partial searching when there is a single value in a search query (via the `_CONTAIN` operator).
- Implement a dropdown next to the search bar for users to specify which fields they'd like to bulk search in. By default, all fields will be checked.
